#!/usr/bin/env bash
#echos best school ten times but hi for 9th
number=1
while [ $number -lt 11 ]
do
	if [ $number -eq 9 ]
	then
		echo "Best School"
		echo "hi"
	else
		echo "Best School"
	fi
	number=$((number+1))
done
