#!/usr/bin/env bash
#bash script that displays numbers from 1 to 20 

i=1
while [ $i -le 20 ]
do
	if [ $i = 4 ]
	then
		echo "4"
		echo "bad luck form China"
	elif [ $i = 9 ]
	then
		echo "9"
		echo "bad luck fom Japan"
	elif [ $i = 17 ]
	then
		echo "17"
		echo "bad luck from Italy"
	else
		echo $i
	fi
	i=$((i+1))
done
